In [31]:
#access the data 
import pandas as pd

In [32]:
df_yummly = pd.read_json(r'yummly.json')

In [33]:
df_yummly

id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [34]:
res = []
for i in df_yummly['ingredients']:
    
    #for j in df_yummly['cuisine']:
    res.append(i)
        #res.append(j)

In [35]:
new_list = []

for row, index in df_yummly.iterrows():
    new = [index.id, index.cuisine, index.ingredients]
    new_list.append(new)

In [36]:
df_yummly['new'] = new_list

In [37]:
df_yummly

id      cuisine                                        ingredients  \
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...   
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...   
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...   
3      22213       indian                [water, vegetable oil, wheat, salt]   
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...   
...      ...          ...                                                ...   
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...   
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...   
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...   
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...   
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...   

                                                     new  
0      [10259, greek, [romaine lettuce, black olives,...  
1      [25693, southern_us, [plain flour, ground pepp...  
2      [20130, filipino, [eggs, pepper, salt, mayonai...  
3      [22213, indian, [water, vegetable oil, wheat, ...  
4      [13162, indian, [black pepper, shallots, cornf...  
...                                                  ...  
39769  [29109, irish, [light brown sugar, granulated ...  
39770  [11462, italian, [KRAFT Zesty Italian Dressing...  
39771  [2238, irish, [eggs, citrus fruit, raisins, so...  
39772  [41882, chinese, [boneless chicken skinless th...  
39773  [2362, mexican, [green chile, jalapeno chilies...  

[39774 rows x 4 columns]

In [38]:
ingr = res

In [39]:
#df_yummly.values[0].tolist()

In [40]:
ingr_list = []
for item in ingr:
    for i in item:
        ingr_list.append(i)

In [41]:
#ingr_list

In [42]:
#from sklearn.feature_extraction.text import TfidfVectorizer
#tf_trial = TfidfVectorizer()
#tf_transf= tf_trial.fit_transform(ingr_list)
#tf_transf.shape

In [43]:
#my_new = tf_trial.fit_transform(df_yummly['ingredients'])

In [44]:
#tf_new = tf_trial.fit_transform(new_list)

In [45]:
#from sklearn.cluster import KMeans
#help(sklearn.cluster)
#help(KMeans)

#km_ingr = KMeans(n_clusters=5)
#km_ingr.fit(tf_transf)

In [46]:
#%time
#%timeit
#km_ingr.labels_

In [47]:
#km_ingr.labels_

In [48]:
#import pandas as pd
#df = pd.DataFrame({'docId': [1,2,3], 
               #'sent': ['This is the first sentence','This is the second sentence', 'This is the third sentence']})

In [49]:
df_yummly['ingredients'].values

array([list(['romaine lettuce', 'black olives', 'grape tomatoes', 'garlic', 'pepper', 'purple onion', 'seasoning', 'garbanzo beans', 'feta cheese crumbles']),
       list(['plain flour', 'ground pepper', 'salt', 'tomatoes', 'ground black pepper', 'thyme', 'eggs', 'green tomatoes', 'yellow corn meal', 'milk', 'vegetable oil']),
       list(['eggs', 'pepper', 'salt', 'mayonaise', 'cooking oil', 'green chilies', 'grilled chicken breasts', 'garlic powder', 'yellow onion', 'soy sauce', 'butter', 'chicken livers']),
       ...,
       list(['eggs', 'citrus fruit', 'raisins', 'sourdough starter', 'flour', 'hot tea', 'sugar', 'ground nutmeg', 'salt', 'ground cinnamon', 'milk', 'butter']),
       list(['boneless chicken skinless thigh', 'minced garlic', 'steamed white rice', 'baking powder', 'corn starch', 'dark soy sauce', 'kosher salt', 'peanuts', 'flour', 'scallions', 'Chinese rice vinegar', 'vodka', 'fresh ginger', 'egg whites', 'broccoli', 'toasted sesame seeds', 'sugar', 'store bought low

In [50]:
#import pandas as pd
#df = pd.DataFrame({'docId': ['Ab','cd','ef'], 
               #'sent': ['This is the first sentence','This is the second sentence', 'This is the third sentence']})

In [51]:
#df

In [52]:
#df_yummly['join'] = df_yummly.ingridients.apply(', '.join)

#df['liststring'] = [','.join(map(str, l)) for l in df['lists']]

df_yummly['join'] = [', '.join(map(str, i)) for i in df_yummly['ingredients']]

In [53]:
#tf_t = tf_trial.fit_transform(df['sent'])

In [54]:
#tf_t

In [55]:
#def list2Str(lst):
    #if type(lst) is list: # apply conversion to list columns
        #return";".join(lst)
    #else:
        #return lst

#df.apply(lambda x: [list2Str(i) for i in x])

In [56]:
df_yummly['new'] =df_yummly[['ingredients']].apply(lambda x: [list2Str(i) for i in x])

In [57]:
df_yummly

id      cuisine                                        ingredients  \
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...   
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...   
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...   
3      22213       indian                [water, vegetable oil, wheat, salt]   
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...   
...      ...          ...                                                ...   
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...   
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...   
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...   
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...   
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...   

                                                     new  \
0      romaine lettuce;black olives;grape tomatoes;ga...   
1      plain flour;ground pepper;salt;tomatoes;ground...   
2      eggs;pepper;salt;mayonaise;cooking oil;green c...   
3                         water;vegetable oil;wheat;salt   
4      black pepper;shallots;cornflour;cayenne pepper...   
...                                                  ...   
39769  light brown sugar;granulated sugar;butter;warm...   
39770  KRAFT Zesty Italian Dressing;purple onion;broc...   
39771  eggs;citrus fruit;raisins;sourdough starter;fl...   
39772  boneless chicken skinless thigh;minced garlic;...   
39773  green chile;jalapeno chilies;onions;ground bla...   

                                                    join  
0      romaine lettuce, black olives, grape tomatoes,...  
1      plain flour, ground pepper, salt, tomatoes, gr...  
2      eggs, pepper, salt, mayonaise, cooking oil, gr...  
3                      water, vegetable oil, wheat, salt  
4      black pepper, shallots, cornflour, cayenne pep...  
...                                                  ...  
39769  light brown sugar, granulated sugar, butter, w...  
39770  KRAFT Zesty Italian Dressing, purple onion, br...  
39771  eggs, citrus fruit, raisins, sourdough starter...  
39772  boneless chicken skinless thigh, minced garlic...  
39773  green chile, jalapeno chilies, onions, ground ...  

[39774 rows x 5 columns]

In [58]:
#from sklearn.feature_extraction.text import TfidfVectorizer
#tf_trial = TfidfVectorizer()
#tf_tr = tf_trial.fit_transform(df_yummly['join'])

In [59]:
#tf_tr.shape

#row, column

(39774, 3051)

In [60]:
#df_yummly.shape

#row, column

(39774, 5)

In [61]:
#from sklearn.cluster import KMeans
#help(sklearn.cluster)
#help(KMeans)

#km_new = KMeans(n_clusters=5)
#km_new.fit(tf_tr)

In [62]:
df_next = df_yummly

In [64]:
df_next.drop(['ingredients'], axis = 1, inplace = True)

In [65]:
df_next.drop(['new'], axis = 1, inplace = True)

In [66]:
df_next

id      cuisine                                               join
0      10259        greek  romaine lettuce, black olives, grape tomatoes,...
1      25693  southern_us  plain flour, ground pepper, salt, tomatoes, gr...
2      20130     filipino  eggs, pepper, salt, mayonaise, cooking oil, gr...
3      22213       indian                  water, vegetable oil, wheat, salt
4      13162       indian  black pepper, shallots, cornflour, cayenne pep...
...      ...          ...                                                ...
39769  29109        irish  light brown sugar, granulated sugar, butter, w...
39770  11462      italian  KRAFT Zesty Italian Dressing, purple onion, br...
39771   2238        irish  eggs, citrus fruit, raisins, sourdough starter...
39772  41882      chinese  boneless chicken skinless thigh, minced garlic...
39773   2362      mexican  green chile, jalapeno chilies, onions, ground ...

[39774 rows x 3 columns]

In [67]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_next['join'],
                                                   df_next['id'],
                                                   test_size = 0.20,
                                                   random_state = 3)
#using ID as label 

In [68]:
#X_train

In [69]:
#X_test

In [98]:
#fitting and transforming training dataset

from sklearn.feature_extraction.text import TfidfVectorizer
tf_model = TfidfVectorizer()
tf_train = tf_model.fit_transform(X_train)


In [99]:
print(tf_train.shape)
train_labels = y_train

(31819, 2934)


In [100]:
#Transforming test dataset

tf_test = tf_trial.transform(X_test)

In [101]:
print(tf_test.shape)
test_labels = X_train

(7955, 2934)


In [75]:
#Skip, it'll take a long time to run

from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans

num_clus = [2,3,4,5,6,7,8,9,10,11,12,13,14,15]

for num in num_clus:
    
    newK = KMeans(n_clusters = num)
    
    sil_Y = newK.fit_predict(tf_train)

    my_score = silhouette_score(tf_train, sil_Y)
    
    #print("For no of clusters =", num, 
          #" The average silhouette_score is :", my_score)
    

For no of clusters = 2  The average silhouette_score is : 0.022375649128187246
For no of clusters = 3  The average silhouette_score is : 0.019435533608160065
For no of clusters = 4  The average silhouette_score is : 0.0205071118298483
For no of clusters = 5  The average silhouette_score is : 0.01851205643970611
For no of clusters = 6  The average silhouette_score is : 0.019825856715787155
For no of clusters = 7  The average silhouette_score is : 0.02065286260489583
For no of clusters = 8  The average silhouette_score is : 0.021311475090165958
For no of clusters = 9  The average silhouette_score is : 0.022300315733334082
For no of clusters = 10  The average silhouette_score is : 0.02065240086961908
For no of clusters = 11  The average silhouette_score is : 0.019976943015945343
For no of clusters = 12  The average silhouette_score is : 0.020058158689551214
For no of clusters = 13  The average silhouette_score is : 0.02003062840575404
For no of clusters = 14  The average silhouette_score 

In [ ]:
'''
For no of clusters = 2  The average silhouette_score is : 0.022375649128187246
For no of clusters = 3  The average silhouette_score is : 0.019435533608160065
For no of clusters = 4  The average silhouette_score is : 0.0205071118298483
For no of clusters = 5  The average silhouette_score is : 0.01851205643970611
For no of clusters = 6  The average silhouette_score is : 0.019825856715787155
For no of clusters = 7  The average silhouette_score is : 0.02065286260489583
For no of clusters = 8  The average silhouette_score is : 0.021311475090165958
For no of clusters = 9  The average silhouette_score is : 0.022300315733334082
For no of clusters = 10  The average silhouette_score is : 0.02065240086961908
For no of clusters = 11  The average silhouette_score is : 0.019976943015945343
For no of clusters = 12  The average silhouette_score is : 0.020058158689551214
For no of clusters = 13  The average silhouette_score is : 0.02003062840575404
For no of clusters = 14  The average silhouette_score is : 0.02021960429956733
For no of clusters = 15  The average silhouette_score is : 0.019703352702554293
'''

In [76]:
from sklearn.cluster import KMeans
#help(sklearn.cluster)
#help(KMeans)

km_train = KMeans(n_clusters = 9)
km_train.fit(tf_train)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=9, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [77]:
km_train.labels_

array([1, 6, 7, ..., 1, 3, 2])

In [78]:
#X_train

In [79]:
#y_train

In [80]:
topn_features = 9
centroids_ord = km_train.cluster_centers_.argsort()[:, ::-1]
centroids_ord

array([[1000, 2121,   47, ..., 1257, 1258,    0],
       [1817, 1028, 2831, ..., 1380, 1381,    0],
       [1185,  752,  662, ..., 1714, 1713,    0],
       ...,
       [2311, 2477, 2360, ..., 1672, 1674,    0],
       [2574, 1665,  374, ...,  628, 2394, 2214],
       [ 513, 1893, 1160, ..., 1692, 1694,    0]], dtype=int64)

In [81]:
km_train_labels = km_train.predict(tf_train)  #labels from k-means clustering

In [82]:
km_train_labels

array([1, 6, 7, ..., 1, 3, 2])

In [112]:
#printing clusters 
n_clusters = 9

for i in range(n_clusters):
    
    print("Cluster %d:" % i),
    
    print()
    
    for item in centroids_ord[i, :10]:
        
        print(' %s' % km_train_labels[item]),
        
    print
    print()



Cluster 0:

 7
 5
 6
 1
 3
 7
 8
 8
 1
 2

Cluster 1:

 5
 6
 2
 8
 5
 5
 0
 6
 1
 6

Cluster 2:

 1
 2
 3
 8
 1
 8
 2
 7
 1
 2

Cluster 3:

 1
 1
 7
 8
 4
 6
 5
 4
 3
 7

Cluster 4:

 8
 4
 6
 4
 5
 1
 5
 6
 4
 1

Cluster 5:

 5
 4
 1
 1
 6
 1
 7
 3
 4
 5

Cluster 6:

 5
 2
 6
 5
 1
 1
 3
 6
 1
 2

Cluster 7:

 3
 1
 8
 4
 1
 1
 8
 7
 0
 5

Cluster 8:

 1
 7
 0
 1
 5
 6
 5
 1
 6
 0



0

In [ ]:
tf_model = TfidfVectorizer()
#tf_train = tf_model.fit_transform(X_train)

tf_i = tf_model.fit(X_train)
tf_j = tf_model.transform(X_train)
#km_train = KMeans(n_clusters = 9)
#km_train.fit(tf_train)


In [106]:
my_input = ['paprika', 'banana', 'tomatoes']

In [107]:
tf_input = TfidfVectorizer()

tf_input_transf = tf_i.transform(my_input)


In [126]:
if_input_fit = km_train.fit(tf_input_transf)

ValueError: n_samples=3 should be >= n_clusters=9

In [108]:
my_predict = km_train.predict(tf_input_transf)  #the labels from k-means clustering 

In [110]:
my_predict

array([7, 7, 5])

In [119]:
from sklearn.linear_model import LogisticRegression
#tf_model = TfidfVectorizer()
#tf_train = tf_model.fit_transform(X_train)
#X_train, X_test, y_train, y_test = train_test_split(df_next['join'],df_next['id'],test_size = 0.20, random_state = 3)

log_reg = LogisticRegression(random_state = 30)
#log_train = log_reg.fit(tf_train, y_train)  -- Taking very long to run

In [ ]:
#if logistic regression run

#log_predict = log_train.predict(X_test)   #appliying the model on X_test 
#log_input_predict = log_reg.predict(tf_input_transf) #predict classification of my input 


In [120]:
from sklearn.neighbors import KNeighborsClassifier

knn_class = KNeighborsClassifier(n_neighbors=7)

In [122]:
knn_class.fit(tf_train, y_train)   #training the model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [124]:
predict_knn = knn_class.predict(tf_test)  #using test set to test the model 

In [125]:
my_knn = knn_class.predict(my_predict)

ValueError: Expected 2D array, got 1D array instead:
array=[7 7 5].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [127]:
tf_knn =knn_class.predict(tf_input_transf) #passsing vectorized input

In [131]:
tf_knn

array([ 2132,  5978, 10083], dtype=int64)